### ISSUE TITLE
Table messed up when displaying line number

### ISSUE THREAD

**Issue by chuxubank** [casouri/valign#16] opened 2020-12-01 14:59 UTC
Test environment: doom sandbox's vanilla Doom.
valign version: 3.0.0

```elisp
Debugger entered--Lisp error: (wrong-type-argument wholenump -4)
  make-string(-4 9472)
  valign--align-separator-row-full((-28 112 84 112) (1 2 3) "\n+-++\n| ||\n+-++\n+-++" -28)
  valign--table-2()
  valign-table-maybe(nil t)
  valign-region(2086 2586)
  #f(compiled-function (fun) #<bytecode 0x1fe1b129f04d>)(valign-region)
  run-hook-wrapped(#f(compiled-function (fun) #<bytecode 0x1fe1b129f04d>) valign-region)
  jit-lock--run-functions(2086 2586)
  jit-lock-fontify-now(2086 2586)
  jit-lock-function(2086)
  redisplay_internal\ \(C\ function\)()
  redisplay()
  sit-for(2)
  execute-extended-command(nil "valign-mode" #("valign-mod" 0 10 (ws-butler-chg chg)))
  funcall-interactively(execute-extended-command nil "valign-mode" #("valign-mod" 0 10 (ws-butler-chg chg)))
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

**Comment by chuxubank** [comment] 2020-12-01 15:23
<img width="812" alt="image" src="https://user-images.githubusercontent.com/17001575/100759565-b6cc1c00-342b-11eb-9686-e921f5629c4a.png">
Only lines show above messed up, others look good.
Do this test require table.el?

**Comment by casouri** [comment] 2020-12-01 15:44
I couldn't reproduce the wholenum error, but the second one you mentioned might be fixed by the last commit. Could you give it a try? Thanks.

**Comment by chuxubank** [comment] 2020-12-02 00:11
<img width="801" alt="image" src="https://user-images.githubusercontent.com/17001575/100811576-e6a01180-3475-11eb-8b6a-b6b63bdcb960.png">

The wholenum error disappeared, but these lines still messed up.

**Comment by casouri** [comment] 2020-12-29 21:46
Does the problem still occur?

**Comment by chuxubank** [comment] 2020-12-30 00:10
Yep, with commit a880928
<details>
    <summary>Line number off</summary>
<img src="https://user-images.githubusercontent.com/17001575/103321711-eba4b080-4a75-11eb-8324-d0febb1f93f8.png"/>
</details>
<details>
    <summary>Line number on</summary>
<img src="https://user-images.githubusercontent.com/17001575/103321769-2c9cc500-4a76-11eb-92bb-d1c9e78c6b9e.png"/>
</details>

**Comment by casouri** [comment] 2020-12-30 00:27
Could you try 1d2ecd2afdb77021eaffc213d9fbbc6d9c38ed82 (latest commit)?

**Comment by chuxubank** [comment] 2020-12-30 00:38
![image](https://user-images.githubusercontent.com/17001575/103322639-d467c200-4a79-11eb-80ee-4c3196d1f948.png)

It's fixed now! thx!
Do the empty lines in second table still have bug?

**Comment by casouri** [comment] 2020-12-30 00:42
Maybe try typing TAB on that table? It doesn't show up on my machine and I have no good guesses on why it appears like that.

**Comment by ZelphirKaltstahl** [comment] 2023-03-19 15:22
Cannot reproduce this problem with my setup (not Doom Emacs and probably heavily customized). Should this be closed?

**Comment by casouri** [comment] 2023-04-10 21:19
Sure, closing.

**Closed as completed by casouri** 2023-04-10 21:19 UTC
